In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset_orb = pd.read_csv('/Users/adithya/Documents/MATLAB/project/cbir_dataset/sample/X_orb_desc_change.csv',header = None)
dataset_lbp = pd.read_csv('/Users/adithya/Documents/MATLAB/project/cbir_dataset/sample/X_lbp_desc2_long.csv',header = None)

In [2]:
target = pd.read_csv('/Users/adithya/Documents/MATLAB/project/cbir_dataset/sample/y_orb_ouput.csv',header = None)

In [3]:
X_orb = dataset_orb
X_lbp = dataset_lbp
y = target

# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
X_train_orb, X_test_orb, y_train, y_test = train_test_split(X_orb, y, test_size = 0.25, random_state = 0)
X_train_lbp, X_test_lbp, y_train, y_test = train_test_split(X_lbp, y, test_size = 0.25, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_orb = sc.fit_transform(X_train_orb)
X_test_orb = sc.transform(X_test_orb)
X_train_lbp = sc.fit_transform(X_train_lbp)
X_test_lbp = sc.transform(X_test_lbp)


/Users/adithya/anaconda3/envs/tensorflow_adithya/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [4]:
# Applying PCA
from sklearn.decomposition import PCA
pca_orb = PCA(n_components = 500)
pca_lbp = PCA(n_components = 500)
#pca_total = PCA()
#pca = PCA(n_components = None)
X_train_orb = pca_orb.fit_transform(X_train_orb)
X_train_lbp = pca_lbp.fit_transform(X_train_lbp)
#X_test = pca_total.transform(X_test)
#explained_variance = pca.explained_va

In [5]:
X_train = np.hstack((X_train_orb,X_train_lbp))
X_test = np.hstack((X_test_orb,X_test_lbp))

In [6]:
from sklearn.preprocessing import OneHotEncoder
from numpy import array
from numpy import argmax
import numpy
from sklearn.preprocessing import LabelEncoder
#values = array(y_train)
#values = numpy.transpose(values)

In [7]:
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(y_train.values.ravel())

In [8]:
from keras.utils import np_utils
categorical_train = np_utils.to_categorical(integer_encoded)

/Users/adithya/anaconda3/envs/tensorflow_adithya/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [9]:
label_encoder = LabelEncoder()
integer_encoded_test = label_encoder.fit_transform(y_test.values.ravel())

In [10]:
categorical_encoded_test = np_utils.to_categorical(integer_encoded_test)

In [11]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [12]:
# encode class values as integers
from keras.utils import np_utils
encoder = LabelEncoder()
encoder.fit(integer_encoded)
encoded_Y = encoder.transform(integer_encoded)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)

In [13]:
from keras.utils import np_utils
encoder_test = LabelEncoder()
encoder_test.fit(integer_encoded_test)
encoded_Y_test = encoder_test.transform(integer_encoded_test)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y_test = np_utils.to_categorical(encoded_Y_test)

In [14]:
dummy_y_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
dummy_y[13]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
dummy_y_test[13]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
X_train.shape

(1186, 1000)

In [18]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
#classifier.add(Dense(output_dim = 843, init = 'uniform', activation = 'relu', input_dim = 1686))
classifier.add(Dense(output_dim = 500, init = 'uniform', activation = 'tanh', input_dim = 1000))

# Adding the second hidden layer
#classifier.add(Dense(output_dim = 422, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 250, init = 'uniform', activation = 'tanh'))

# Adding the second hidden layer
#classifier.add(Dense(output_dim = 211, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 125, init = 'uniform', activation = 'tanh'))

# Adding the second hidden layer
#classifier.add(Dense(output_dim = 106, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 63, init = 'uniform', activation = 'tanh'))

# Adding the second hidden layer
#classifier.add(Dense(output_dim = 53, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 32, init = 'uniform', activation = 'tanh'))

# Adding the second hidden layer
#classifier.add(Dense(output_dim = 27, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 16, init = 'uniform', activation = 'tanh'))

# Adding the output layer
#classifier.add(Dense(output_dim = 14, init = 'uniform', activation = 'sigmoid'))
classifier.add(Dense(output_dim = 14, init = 'uniform', activation = 'softmax'))

# Compiling the ANN
#classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
#classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['categorical_accuracy'])
classifier.compile(optimizer = 'sgd', loss = 'categorical_crossentropy', metrics = ['categorical_accuracy'])
#classifier.compile(optimizer = 'sgd', loss = 'categorical_hinge', metrics = ['categorical_accuracy'])

/Users/adithya/anaconda3/envs/tensorflow_adithya/lib/python3.6/site-packages/ipykernel_launcher.py:13: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="tanh", input_dim=1000, units=500, kernel_initializer="uniform")`
  del sys.path[0]
/Users/adithya/anaconda3/envs/tensorflow_adithya/lib/python3.6/site-packages/ipykernel_launcher.py:17: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="tanh", units=250, kernel_initializer="uniform")`
/Users/adithya/anaconda3/envs/tensorflow_adithya/lib/python3.6/site-packages/ipykernel_launcher.py:21: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="tanh", units=125, kernel_initializer="uniform")`
/Users/adithya/anaconda3/envs/tensorflow_adithya/lib/python3.6/site-packages/ipykernel_launcher.py:25: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="tanh", units=63, kernel_initializer="uniform")`
/Users/adithya/anaconda3/envs/tensorflow_adithya/li

In [19]:
# Fitting the ANN to the Training set
classifier.fit(X_train, dummy_y, batch_size = 10, epochs = 100)

Epoch 1/100
1186/1186 [==============================] - 3s 2ms/step - loss: 2.5911 - categorical_accuracy: 0.3153
Epoch 2/100
1186/1186 [==============================] - 1s 900us/step - loss: 2.5052 - categorical_accuracy: 0.3187
Epoch 3/100
1186/1186 [==============================] - 1s 1ms/step - loss: 2.4358 - categorical_accuracy: 0.3187
Epoch 4/100
1186/1186 [==============================] - 1s 963us/step - loss: 2.3816 - categorical_accuracy: 0.3187
Epoch 5/100
1186/1186 [==============================] - 1s 944us/step - loss: 2.3399 - categorical_accuracy: 0.3187
Epoch 6/100
1186/1186 [==============================] - 1s 955us/step - loss: 2.3091 - categorical_accuracy: 0.3187
Epoch 7/100
1186/1186 [==============================] - 1s 1ms/step - loss: 2.2857 - categorical_accuracy: 0.3187
Epoch 8/100
1186/1186 [==============================] - 1s 1ms/step - loss: 2.2685 - categorical_accuracy: 0.3187
Epoch 9/100
1186/1186 [==============================] - 1s 985us/step -

In [20]:
from keras.models import load_model
classifier.save('my_model2last.h5')  # creates a HDF5 file 'my_model.h5'

In [21]:
database = classifier.predict(X_train)

In [22]:
import pandas as pd 
df = pd.DataFrame(database)
df.to_csv("/Users/adithya/Documents/MATLAB/project/cbir_dataset/sample/predicted_pca.csv")